name: Restore Cache

runs:
  steps:
    - name: Cache Setup
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
    - name: Cache nx
      uses: actions/cache@v4
      with:
        path: .nx
        key: ${{ runner.os }}-nx
  using: composite
