import {
  type ActionInputs,
  type Constructable,
  type IUnknownModelAction,
  type IUnknownResourceAction,
  NodeType,
  type TransactionOptions,
  type UnknownModel,
  type UnknownOverlay,
  type UnknownResource,
  ValidationType,
} from '../../app.type.js';
import { EventSource } from '../../decorators/event-source.decorator.js';
import { Factory } from '../../decorators/factory.decorator.js';
import {
  InputNotFoundTransactionError,
  InputRegistrationError,
  ResourceActionExceptionTransactionError,
  ResourceActionTimeoutTransactionError,
  TransactionError,
  ValidationTransactionError,
} from '../../errors/index.js';
import {
  ModelActionRegistrationEvent,
  ModelActionTransactionEvent,
  ModelDiffsTransactionEvent,
  ModelTransactionTransactionEvent,
  ResourceActionCompletedTransactionEvent,
  ResourceActionInitiatedTransactionEvent,
  ResourceActionRegistrationEvent,
  ResourceActionSummaryTransactionEvent,
  ResourceDiffsTransactionEvent,
  ResourceTransactionTransactionEvent,
} from '../../events/index.js';
import { Container } from '../../functions/container/container.js';
import { DiffMetadata } from '../../functions/diff/diff-metadata.js';
import { type Diff, DiffAction } from '../../functions/diff/diff.js';
import { DiffUtility } from '../../functions/diff/diff.utility.js';
import type { ANode } from '../../functions/node/node.abstract.js';
import type { AModel } from '../../models/model.abstract.js';
import { ModuleContainer } from '../../modules/module.container.js';
import { OverlayDataRepository } from '../../overlays/overlay-data.repository.js';
import { AOverlay } from '../../overlays/overlay.abstract.js';
import { ResourceDataRepository } from '../../resources/resource-data.repository.js';
import { AResource } from '../../resources/resource.abstract.js';
import { ATerraformResource } from '../../resources/terraform-resource.abstract.js';
import { EventService } from '../event/event.service.js';
import { InputService } from '../input/input.service.js';
import { TerraformService } from '../terraform/terraform.service.js';

/**
 * No-op resource action backing terraform resource diffs. Terraform manages the resource's lifecycle;
 * octo only carries the diff for review and validation.
 *
 * @internal
 */
class TerraformNoopResourceAction implements IUnknownResourceAction {
  filter(): boolean {
    return true;
  }

  async handle(): Promise<void> {}
}

/**
 * @internal
 */
export class TransactionService {
  private modelActions: { modelClass: Constructable<UnknownModel>; actions: IUnknownModelAction[] }[] = [];
  private overlayActions: { overlayClass: Constructable<UnknownOverlay>; actions: IUnknownModelAction[] }[] = [];
  private resourceActions: { resourceClass: Constructable<UnknownResource>; actions: IUnknownResourceAction[] }[] = [];

  constructor(
    private readonly eventService: EventService,
    private readonly inputService: InputService,
    private readonly moduleContainer: ModuleContainer,
    private readonly overlayDataRepository: OverlayDataRepository,
    private readonly resourceDataRepository: ResourceDataRepository,
    private readonly terraformService: TerraformService,
  ) {}

  private async applyModels(diffs: DiffMetadata[]): Promise<DiffMetadata[][]> {
    const transaction: DiffMetadata[][] = [];

    let currentApplyOrder = 0;
    let processed = 0;

    while (processed < diffs.length) {
      const diffsInSameLevel = diffs.filter((d) => d.applyOrder === currentApplyOrder);
      const diffsProcessedInSameLevel: DiffMetadata[] = [];

      for (const diff of diffsInSameLevel) {
        if (diff.applied) {
          continue;
        }

        // Check for duplicate diffs on the same model and same field.
        const duplicateDiffs = this.getDuplicateDiffs(diff, diffsInSameLevel);

        // Only process the first diff, given all duplicate diffs are the same.
        const diffToProcess = duplicateDiffs[0].diff;

        for (const a of diff.actions as IUnknownModelAction[]) {
          // Find moduleId.
          let moduleId: string;
          if (diff.node instanceof AOverlay) {
            moduleId = this.inputService.getModuleIdFromOverlay(diff.node);
          } else {
            moduleId = this.inputService.getModuleIdFromModel(diff.node as UnknownModel);
          }

          // Resolve all keys of the module - inputs keys and nodes generated by the module keys.
          const inputs: ActionInputs = { inputs: {}, metadata: {}, models: {}, overlays: {}, resources: {} };
          const inputKeys = this.moduleContainer.getModuleInstanceInputKeys(moduleId).map((i) => {
            return `${moduleId}.input.${i}`;
          });
          const metadataKeys = this.inputService.getMetadataKeys(moduleId);
          const nodeKeys = this.inputService.getAllNodeKeys(moduleId);
          const allKeys = [...inputKeys, ...metadataKeys, ...nodeKeys];

          for (const k of allKeys) {
            const inputValue = this.inputService.resolve(k);
            if (inputValue === undefined) {
              throw new InputNotFoundTransactionError(
                'No matching input found to process action!',
                a,
                diffToProcess,
                k,
              );
            }

            const keyValue = k.split('.')[2];
            if (k.startsWith(`${moduleId}.input`)) {
              inputs.inputs[keyValue] = inputValue;
            } else if (k.startsWith(`${moduleId}.metadata`)) {
              inputs.metadata[keyValue] = inputValue;
            } else if (k.startsWith(`${moduleId}.model`)) {
              inputs.models[keyValue] = inputValue as UnknownModel;
            } else if (k.startsWith(`${moduleId}.overlay`)) {
              inputs.overlays[keyValue] = inputValue as UnknownOverlay;
            } else if (k.startsWith(`${moduleId}.resource`)) {
              inputs.resources[keyValue] = inputValue as UnknownResource;
            }
          }

          // Apply all actions on the diff, then update diff metadata with inputs and outputs.
          const outputs = await a.handle(diffToProcess, inputs, {});
          for (const resource of Object.values(outputs)) {
            let moduleId: string;
            if (diffToProcess.node instanceof AOverlay) {
              moduleId = this.inputService.getModuleIdFromOverlay(diffToProcess.node);
            } else {
              moduleId = this.inputService.getModuleIdFromModel(diffToProcess.node as UnknownModel);
            }

            // Set resource tags.
            const resourceTags = this.inputService.resolve(`${moduleId}.tag.${resource.getContext()}`) as {
              [key: string]: string;
            };
            for (const [key, value] of Object.entries(resourceTags)) {
              resource.tags[key] = value;
            }

            const previousResource = this.resourceDataRepository.getNewResourceByContext(resource.getContext());
            if (previousResource) {
              resource.merge(previousResource);
            } else {
              this.resourceDataRepository.addNewResource(resource);
            }

            try {
              this.inputService.registerResource(moduleId, resource);
            } catch (error) {
              if (!(error instanceof InputRegistrationError)) {
                throw error;
              }
            }
          }

          duplicateDiffs.forEach((d) => {
            d.updateInputs(inputs);
            d.updateOutputs(outputs);
          });

          this.eventService.emit(new ModelActionTransactionEvent(a.constructor.name));
        }

        // Include the diff to process in the list of diffs processed in the same level.
        diffsProcessedInSameLevel.push(duplicateDiffs[0]);

        // Mark metadata of each duplicate diffs as applied.
        duplicateDiffs.forEach((d) => (d.applied = true));
      }

      // Add all diff in same level to transaction.
      transaction.push(diffsProcessedInSameLevel);

      processed += diffsInSameLevel.length;
      currentApplyOrder += 1;
    }

    return transaction;
  }

  private async applyResources(
    diffs: DiffMetadata[],
    { skipActualResourceUpdate = false }: { skipActualResourceUpdate?: boolean } = {},
  ): Promise<DiffMetadata[][]> {
    const transaction: DiffMetadata[][] = [];
    const validationErrors: Error[] = [];

    let currentApplyOrder = 0;
    let processed = 0;

    while (processed < diffs.length) {
      const diffsInSameLevel = diffs.filter((d) => d.applyOrder === currentApplyOrder);
      const diffsProcessedInSameLevel: DiffMetadata[] = [];

      for (const diff of diffsInSameLevel) {
        if (diff.applied) {
          continue;
        }

        // Check for duplicate diffs on the same resource and same field.
        const duplicateDiffs = this.getDuplicateDiffs(diff, diffsInSameLevel);

        // Only process the first diff, given all duplicate diffs are the same.
        const diffToProcess = duplicateDiffs[0].diff;

        for (const a of diff.actions as IUnknownResourceAction[]) {
          this.eventService.emit(new ResourceActionInitiatedTransactionEvent(a.constructor.name, diff));

          let actionTimeoutId: NodeJS.Timeout | undefined;
          try {
            await Promise.race([
              new Promise<void>(async (resolve, reject) => {
                try {
                  const response = await a.handle(diffToProcess);
                  this.resourceDataRepository
                    .getNewResourceByContext(diffToProcess.node.getContext())
                    ?.setResponse(response);
                  resolve();
                } catch (error) {
                  if (diffToProcess.action === DiffAction.VALIDATE) {
                    validationErrors.push(error);
                    resolve();
                  } else {
                    reject(
                      new ResourceActionExceptionTransactionError(
                        error.message,
                        error,
                        diffToProcess,
                        a.constructor.name,
                      ),
                    );
                  }
                }
              }),
              new Promise(
                (_resolve, reject) =>
                  (actionTimeoutId = setTimeout(() => {
                    reject(
                      new ResourceActionTimeoutTransactionError(
                        `Resource action ${a.constructor.name} timed out after ${a.actionTimeoutInMs || 90000}ms!`,
                        diffToProcess,
                        a.constructor.name,
                      ),
                    );
                  }, a.actionTimeoutInMs || 90000)), // 1.5 minutes.
              ),
            ]);
          } finally {
            if (actionTimeoutId) {
              clearTimeout(actionTimeoutId);
            }
          }

          if (skipActualResourceUpdate) {
            // Stateless invocation (run-action): the actual resource graph is not maintained;
            // terraform state is the source of truth until the next commit.
            this.eventService.emit(new ResourceActionCompletedTransactionEvent(a.constructor.name, diff));
            continue;
          }

          // De-reference from actual resources.
          const deReferenceResource = async (context: string): Promise<UnknownResource> => {
            return this.resourceDataRepository.getActualResourceByContext(context)!;
          };

          // Incrementally apply diff inverse to the respective actual resource.
          let actualResource = this.resourceDataRepository.getActualResourceByContext(diffToProcess.node.getContext())!;
          if (!actualResource) {
            actualResource = await AResource.cloneResource(diffToProcess.node as UnknownResource, deReferenceResource);
            this.resourceDataRepository.addActualResource(actualResource);
            this.eventService.emit(
              new ResourceActionSummaryTransactionEvent(a.constructor.name, {
                diff,
                values: { current: actualResource.synth(), previous: {} },
              }),
            );
          } else {
            const previousSynth = actualResource.synth();
            await actualResource.diffInverse(diffToProcess, deReferenceResource);
            this.eventService.emit(
              new ResourceActionSummaryTransactionEvent(a.constructor.name, {
                diff,
                values: {
                  current: actualResource.isMarkedDeleted() ? {} : actualResource.synth(),
                  previous: previousSynth,
                },
              }),
            );
          }

          this.eventService.emit(new ResourceActionCompletedTransactionEvent(a.constructor.name, diff));
        }

        // Include the diff to process in the list of diffs processed in the same level.
        diffsProcessedInSameLevel.push(duplicateDiffs[0]);

        // Mark metadata of each duplicate diffs as applied.
        duplicateDiffs.forEach((d) => (d.applied = true));
      }

      // Add all diff in same level to transaction.
      transaction.push(diffsProcessedInSameLevel);

      processed += diffsInSameLevel.length;
      currentApplyOrder += 1;
    }

    if (validationErrors.length > 0) {
      throw new ValidationTransactionError('Validation failed on resources!', {
        errors: validationErrors.map((error) => ({
          constraint: 'Resource Validation',
          type: ValidationType.CUSTOM,
          value: error.message,
        })),
        pass: false,
      });
    }

    return transaction;
  }

  /**
   * Contributes every resource in the new (desired) resource graph to the shared
   * {@link TerraformService}: terraform resources via `toHCL()`, external resources via
   * `addOctoTerraformExternalResource()`. Always processes the full desired state — terraform
   * computes the actual create/update/delete against its own state.
   *
   * Order does not matter: terraform resources reference each other through deferred refs, and
   * external resources defer their parent-input wiring — both are resolved later, once every
   * resource is registered (see {@link TerraformService}'s wiring phase).
   */
  private async generateTerraform(): Promise<void> {
    this.terraformService.reset();

    const resources = this.resourceDataRepository.getNewResourcesByProperties().filter((r) => !r.isMarkedDeleted());

    for (const resource of resources) {
      // Every resource is produced by a model action inside a module, so it is always module-bound.
      // A missing attribution means the resource was registered out-of-band — a hard error.
      const moduleId = this.inputService.getModuleIdFromResource(resource);
      if (moduleId === undefined) {
        throw new TransactionError(`Resource "${resource.resourceId}" is not associated with any module!`);
      }

      const scope = this.terraformService.scope(moduleId);
      if (resource instanceof ATerraformResource) {
        await resource.toHCL(scope);
      } else {
        scope.addOctoTerraformExternalResource(resource);
      }
    }
  }

  private getDiffsOfSameNode(diff: DiffMetadata, diffs: DiffMetadata[], diffAction: DiffAction): DiffMetadata[] {
    return diffs.filter((d) => d.node.getContext() === diff.node.getContext() && d.action === diffAction);
  }

  private getDuplicateDiffs(diff: DiffMetadata, diffs: DiffMetadata[]): DiffMetadata[] {
    return diffs.filter(
      (d) =>
        d.node.getContext() === diff.node.getContext() &&
        d.field === diff.field &&
        d.action === diff.action &&
        DiffUtility.isObjectDeepEquals(d.value, diff.value),
    );
  }

  private getMatchingDiffs(diff: DiffMetadata, diffs: DiffMetadata[]): DiffMetadata[] {
    return diffs.filter(
      (d) =>
        d.node.getContext() === diff.node.getContext() &&
        d.field === diff.field &&
        DiffUtility.isObjectDeepEquals(d.value, diff.value),
    );
  }

  /**
   * Before assigning order to a diff, all its node's parent diffs must be processed.
   * E.g. diff to add environment, depends on region to exist, thus add region diff gets processed first.
   */
  private setApplyOrder(diff: DiffMetadata, diffs: DiffMetadata[], seen: DiffMetadata[] = []): void {
    // Detect circular dependencies.
    if (this.getDuplicateDiffs(diff, seen).length > 0) {
      throw new TransactionError('Found circular dependencies!');
    }

    // Detect conflicting actions in transaction.
    const matchingDiffs = this.getMatchingDiffs(diff, diffs);
    const diffActions = matchingDiffs.reduce((accumulator, currentValue) => {
      accumulator[currentValue.action] = true;
      return accumulator;
    }, {});
    if (diffActions[DiffAction.ADD] && diffActions[DiffAction.DELETE]) {
      throw new TransactionError('Found conflicting actions in same transaction!');
    }

    // Skip processing diff that already has the applyOrder set.
    if (diff.applyOrder >= 0) {
      return;
    }

    // Get all dependencies of subject node.
    const dependencies = diff.node.getDependencies();
    const dependencyApplyOrders: number[] = [-1];

    for (const dependency of dependencies) {
      // Iterate diffs looking to match dependency on same field and action.
      const matchingParentDiffs = diffs.filter(
        (d) =>
          d.node.getContext() === dependency.to.getContext() &&
          dependency.hasMatchingBehavior(diff.field, diff.action, d.field, d.action),
      );

      // On each diff that should be processed first, apply order on it before than self.
      for (const matchingParentDiff of matchingParentDiffs) {
        this.setApplyOrder(matchingParentDiff, diffs, [...seen, diff]);
        dependencyApplyOrders.push(matchingParentDiff.applyOrder);
      }
    }

    // Get diffs of same node.
    // Process ADD before UPDATE/REPLACE, and UPDATE/REPLACE before DELETE. A REPLACE recreates the
    // resource in place (same context), so for ordering it behaves like an UPDATE.
    if (diff.action === DiffAction.UPDATE || diff.action === DiffAction.REPLACE) {
      const diffsOfSameNodeWithAddAction = this.getDiffsOfSameNode(diff, diffs, DiffAction.ADD);
      for (const sameNodeDiffWithAddAction of diffsOfSameNodeWithAddAction) {
        this.setApplyOrder(sameNodeDiffWithAddAction, diffs, [...seen, diff]);
        dependencyApplyOrders.push(sameNodeDiffWithAddAction.applyOrder);
      }
    } else if (diff.action === DiffAction.DELETE) {
      const diffsOfSameNodeWithUpdateAction = this.getDiffsOfSameNode(diff, diffs, DiffAction.UPDATE);
      for (const sameNodeDiffWithUpdateAction of diffsOfSameNodeWithUpdateAction) {
        this.setApplyOrder(sameNodeDiffWithUpdateAction, diffs, [...seen, diff]);
        dependencyApplyOrders.push(sameNodeDiffWithUpdateAction.applyOrder);
      }
    }

    diff.applyOrder = Math.max(...dependencyApplyOrders) + 1;
  }

  async *beginTransaction(
    diffs: Diff[],
    {
      enableResourceValidation = false,
      filterResourceDiffsByResourceId = undefined,
      generateTerraform = false,
      skipActualResourceUpdate = false,
      yieldModelDiffs = false,
      yieldModelTransaction = false,
      yieldResourceDiffs = false,
      yieldResourceTransaction = false,
    }: TransactionOptions = {},
  ): AsyncGenerator<DiffMetadata[][], DiffMetadata[][]> {
    // Diff overlays and add to existing diffs.
    const overlayDiffs = await this.overlayDataRepository.diff();
    diffs.push(...overlayDiffs);

    // Generate diff on models.
    const modelDiffs = diffs.map((d) => {
      if ((d.node.constructor as typeof ANode).NODE_TYPE === NodeType.OVERLAY) {
        return new DiffMetadata(
          d,
          (
            this.overlayActions.find(
              (a) => (a.overlayClass as unknown as typeof AOverlay) === (d.node.constructor as typeof AOverlay),
            )?.actions || []
          ).filter((a) => a.filter(d)),
        );
      } else {
        return new DiffMetadata(
          d,
          (
            this.modelActions.find(
              (a) => (a.modelClass as unknown as typeof AModel) === (d.node.constructor as typeof AModel),
            )?.actions || []
          ).filter((a) => a.filter(d)),
        );
      }
    });
    // Set apply order on model diffs.
    for (const diff of modelDiffs) {
      this.setApplyOrder(diff, modelDiffs);
    }

    this.eventService.emit(new ModelDiffsTransactionEvent(undefined, [modelDiffs]));
    if (yieldModelDiffs) {
      yield [modelDiffs];
    }

    // Apply model diffs.
    const modelTransaction = await this.applyModels(modelDiffs);

    this.eventService.emit(new ModelTransactionTransactionEvent(undefined, modelTransaction));
    if (yieldModelTransaction) {
      yield modelTransaction;
    }

    // Generate resource diffs.
    let newDiffs = await this.resourceDataRepository.diff();
    let dirtyDiffs = await this.resourceDataRepository.diffDirty();

    // Scope diffs to a single resource, e.g. when terraform invokes octo for one resource action.
    if (filterResourceDiffsByResourceId !== undefined) {
      newDiffs = newDiffs.filter((d) => (d.node as UnknownResource).resourceId === filterResourceDiffsByResourceId);
      dirtyDiffs = dirtyDiffs.filter((d) => (d.node as UnknownResource).resourceId === filterResourceDiffsByResourceId);

      // Prefer dirty diffs (actual-graph nodes) over equal new diffs (old-graph nodes) for
      // execution: deserialized old resources are frozen and cannot receive injected inputs.
      for (let i = newDiffs.length - 1; i >= 0; i--) {
        const newDiff = newDiffs[i];
        if (
          dirtyDiffs.some(
            (d) =>
              d.node.getContext() === newDiff.node.getContext() &&
              d.action === newDiff.action &&
              d.field === newDiff.field &&
              DiffUtility.isObjectDeepEquals(d.value, newDiff.value),
          )
        ) {
          newDiffs.splice(i, 1);
        }
      }
    }

    if (enableResourceValidation && (newDiffs.length > 0 || dirtyDiffs.length > 0)) {
      throw new TransactionError('Cannot run resource validation with pending resource diffs!');
    }

    if (enableResourceValidation) {
      const validationDiffs = this.resourceDataRepository.diffValidate();
      newDiffs.push(...validationDiffs);
      dirtyDiffs.push(...validationDiffs);
    }

    // new diffs = new - old | dirty diffs = new - actual
    // Any new diff that is also not part of dirty diffs should be skipped, as the actual is already in desired state.
    for (let i = newDiffs.length - 1; i >= 0; i--) {
      const newDiff = newDiffs[i];
      if (
        !dirtyDiffs.some(
          (d) =>
            d.node.getContext() === newDiff.node.getContext() &&
            d.action === newDiff.action &&
            d.field === newDiff.field &&
            DiffUtility.isObjectDeepEquals(d.value, newDiff.value),
        )
      ) {
        newDiffs.splice(i, 1);
      }
    }

    // Ensure any new diffs are not operating on dirty resources.
    this.resourceDataRepository.ensureDiffsNotOperatingOnDirtyResources(newDiffs);

    // Skip processing dirty diffs that are already accounted for in new diffs.
    for (let i = dirtyDiffs.length - 1; i >= 0; i--) {
      const dirtyDiff = dirtyDiffs[i];
      if (
        newDiffs.some(
          (d) =>
            d.node.getContext() === dirtyDiff.node.getContext() &&
            d.action === dirtyDiff.action &&
            d.field === dirtyDiff.field &&
            DiffUtility.isObjectDeepEquals(d.value, dirtyDiff.value),
        )
      ) {
        dirtyDiffs.splice(i, 1);
      }
    }

    // Terraform resources have no resource actions - terraform owns their lifecycle. Their diffs
    // remain part of the transaction as review artifacts, backed by a no-op action.
    const resolveResourceActions = (d: Diff): IUnknownResourceAction[] => {
      if (d.node instanceof ATerraformResource) {
        return [new TerraformNoopResourceAction()];
      }
      return (
        this.resourceActions.find(
          (a) => (a.resourceClass as unknown as typeof AResource) === (d.node.constructor as typeof AResource),
        )?.actions || []
      ).filter((a) => a.filter(d));
    };

    // Generate diff on resources.
    const resourceDiffs = newDiffs.map((d) => new DiffMetadata(d, resolveResourceActions(d)));
    // Set apply order on resource diffs.
    for (const diff of resourceDiffs) {
      this.setApplyOrder(diff, resourceDiffs);
    }
    // Generate diff on dirty resources.
    const dirtyResourceDiffs = dirtyDiffs.map((d) => new DiffMetadata(d, resolveResourceActions(d)));
    // Set apply order on dirty resource diffs.
    for (const diff of dirtyResourceDiffs) {
      this.setApplyOrder(diff, dirtyResourceDiffs);
    }

    // Contribute the full desired resource graph to terraform. Deferred until after resource diffs
    // are computed and ordered, so an author refusal (a throw in diff*) or an ordering/cycle error
    // aborts generation before any HCL is built — diffs gate generation.
    if (generateTerraform) {
      await this.generateTerraform();
    }

    this.eventService.emit(new ResourceDiffsTransactionEvent(undefined, [[resourceDiffs], [dirtyResourceDiffs]]));
    if (yieldResourceDiffs) {
      yield [resourceDiffs, dirtyResourceDiffs];
    }

    // Apply resource diffs.
    const resourceTransaction = await this.applyResources(resourceDiffs, { skipActualResourceUpdate });
    // Apply dirty resource diffs.
    const dirtyResourceTransaction = await this.applyResources(dirtyResourceDiffs, { skipActualResourceUpdate });

    this.eventService.emit(
      new ResourceTransactionTransactionEvent(undefined, [resourceTransaction, dirtyResourceTransaction]),
    );
    if (yieldResourceTransaction) {
      yield [...resourceTransaction, ...dirtyResourceTransaction];
    }

    return modelTransaction;
  }

  @EventSource(ModelActionRegistrationEvent)
  registerModelActions(forModel: Constructable<UnknownModel>, actions: IUnknownModelAction[]): void {
    const modelActions = this.modelActions.find((a) => a.modelClass === forModel);
    if (!modelActions) {
      this.modelActions.push({ actions: actions, modelClass: forModel });
    } else {
      for (const action of actions) {
        if (modelActions.actions.find((a) => a.constructor.name === action.constructor.name)) {
          throw new Error(`Action "${action.constructor.name}" already registered for model "${forModel.name}"!`);
        }
        modelActions.actions.push(action);
      }
    }
  }

  @EventSource(ModelActionRegistrationEvent)
  registerOverlayActions(forOverlay: Constructable<UnknownOverlay>, actions: IUnknownModelAction[]): void {
    const overlayActions = this.overlayActions.find((a) => a.overlayClass === forOverlay);
    if (!overlayActions) {
      this.overlayActions.push({ actions: actions, overlayClass: forOverlay });
    } else {
      for (const action of actions) {
        if (overlayActions.actions.find((a) => a.constructor.name === action.constructor.name)) {
          throw new Error(`Action "${action.constructor.name}" already registered for overlay "${forOverlay.name}"!`);
        }
        overlayActions.actions.push(action);
      }
    }
  }

  @EventSource(ResourceActionRegistrationEvent)
  registerResourceActions(forResource: Constructable<UnknownResource>, actions: IUnknownResourceAction[]): void {
    if (forResource.prototype instanceof ATerraformResource) {
      throw new TransactionError(
        `Cannot register resource actions for terraform resource "${forResource.name}"! ` +
          'Terraform resources are managed by terraform via toHCL().',
      );
    }

    const resourceActions = this.resourceActions.find((a) => a.resourceClass === forResource);
    if (!resourceActions) {
      this.resourceActions.push({ actions: actions, resourceClass: forResource });
    } else {
      for (const action of actions) {
        if (resourceActions.actions.find((a) => a.constructor.name === action.constructor.name)) {
          throw new Error(`Action "${action.constructor.name}" already registered for resource "${forResource.name}"!`);
        }
        resourceActions.actions.push(action);
      }
    }
  }

  unregisterModelActions(forModel: Constructable<UnknownModel>): void {
    const modelActions = this.modelActions.find((a) => a.modelClass === forModel);
    if (!modelActions) {
      return;
    }

    modelActions.actions = [];
  }

  unregisterOverlayActions(forOverlay: Constructable<UnknownOverlay>): void {
    const overlayActions = this.overlayActions.find((a) => a.overlayClass === forOverlay);
    if (!overlayActions) {
      return;
    }

    overlayActions.actions = [];
  }
}

/**
 * @internal
 */
@Factory<TransactionService>(TransactionService)
export class TransactionServiceFactory {
  private static instance: TransactionService;

  static async create(): Promise<TransactionService> {
    const container = Container.getInstance();
    const [
      eventService,
      inputService,
      moduleContainer,
      overlayDataRepository,
      resourceDataRepository,
      terraformService,
    ] = await Promise.all([
      container.get(EventService),
      container.get(InputService),
      container.get(ModuleContainer),
      container.get(OverlayDataRepository),
      container.get(ResourceDataRepository),
      container.get(TerraformService),
    ]);

    if (!this.instance) {
      this.instance = new TransactionService(
        eventService,
        inputService,
        moduleContainer,
        overlayDataRepository,
        resourceDataRepository,
        terraformService,
      );
    }

    return this.instance;
  }
}
