name: Manual Release

on:
  workflow_dispatch:
    inputs:
      branch:
        default: 'main'
        description: 'Select the branch you want to release.'
        options:
          - main
        required: true
        type: choice

jobs:
  build-release:
    continue-on-error: false
    name: Build & Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      - name: Setup Git
        run: |
          git config --local user.email "rahul300chaudhary400@gmail.com"
          git config --local user.name "Rahul Chaudhary"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ./node_modules/.bin/nx run-many -t build -p @quadnix/octo @quadnix/octo-aws-cdk @quadnix/octo-build
      - name: Pre Release
        run: |
          jq -S '. + (input|{bugs, homepage, keywords, license, repository})' packages/octo/package.json package.json > out.json
          mv out.json packages/octo/package.json
          cp README.md packages/octo/README.md
          jq -S '. + (input|{bugs, homepage, keywords, license, repository})' packages/octo-aws-cdk/package.json package.json > out.json
          mv out.json packages/octo-aws-cdk/package.json
          cp README.md packages/octo-aws-cdk/README.md
          jq -S '. + (input|{bugs, homepage, keywords, license, repository})' packages/octo-build/package.json package.json > out.json
          mv out.json packages/octo-build/package.json
          cp README.md packages/octo-build/README.md
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Release
        run: |
          gh auth status
          git config --list
          ./node_modules/.bin/nx release --yes
