name: "Pull Request Workflow"
on:
  pull_request:
    types:
      - converted_to_draft
      - edited
      - opened
      - ready_for_review
      - synchronize
jobs:
  validate-pr-title:
    name: Validate PR Title
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/validate-pr-title.config.json
