name: "Pull Request Workflow"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  pr-quality-check:
    continue-on-error: false
    name: PR Quality Check
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate PR Title
        run: |-
          .github/jobs/validate-pr-title.job.sh "${{ github.event.pull_request.title }}"

  restore-cache:
    continue-on-error: true
    name: Restore Cache
    needs: [pr-quality-check]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore Cache
        uses: ./.github/actions/restore-cache
      - id: restore-cache-install-dependencies
        name: Install Dependencies
        run: npm install
      - if: steps.restore-cache-install-dependencies.outcome == 'failure'
        name: Bust Cache
        run: |-
          rm -rf node_modules
          npm install

  code-quality-check:
    continue-on-error: false
    name: Code Quality Check
    needs: [restore-cache]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore Cache
        uses: ./.github/actions/restore-cache
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  build-check:
    continue-on-error: false
    name: Build Check
    needs: [restore-cache]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore Cache
        uses: ./.github/actions/restore-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ./node_modules/.bin/nx run-many -t build -p @quadnix/octo @quadnix/octo-aws-cdk @quadnix/octo-build @quadnix/octo-event-listeners
      - name: Unit Tests
        run: npm test
