name: "Pull Request Workflow"

on:
  pull_request:
    types:
      - converted_to_draft
      - edited
      - opened
      - ready_for_review
      - synchronize

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  validate-pr-title:
    continue-on-error: true
    name: Validate PR Title
    needs: [checkout]
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - run: |-
          sh .github/jobs/validate-pr-title.sh
