name: "Pull Request Workflow"

on:
  pull_request:
    types:
      - converted_to_draft
      - edited
      - opened
      - ready_for_review
      - synchronize

jobs:
  cache-restore:
    continue-on-error: true
    name: Cache Restore
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Setup
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - id: cache-primes
        name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install

  pr-quality-check:
    continue-on-error: false
    name: PR Quality Check
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate PR Title
        run: |-
          .github/jobs/validate-pr-title.sh "${{ github.event.pull_request.title }}"

  code-quality-check:
    continue-on-error: false
    name: Code Quality Check
    needs: [cache-restore]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Setup
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - id: cache-primes
        name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  build-check:
    continue-on-error: false
    name: Build Check
    needs: [cache-restore]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Setup
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - id: cache-primes
        name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Unit Tests
        run: npm test
